server:
  port: 8080

spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"
      routes:
      - id: tests
        uri: http://localhost:8083/
        predicates:
        - Path=/tests/**
      - id: PERSON_SERVICE
        uri: http://localhost:8081/
        predicates:
        - Path=/PERSON_SERVICE/**
      - id: testcenter
        uri: http://localhost:8082/
        predicates:
        - Path=/testcenter/**
  application:
    name: apigateway